language: ruby
rvm:
 - 2.2
before_install:
  #GOSU dependencies
  - pwd
  - sudo apt-get -qq update
  - cd ~
  - mkdir sdl2install
  - export SDL2DIR="`pwd`/sdl2install"
  - wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar xzf SDL2-2.0.3.tar.gz
  - cd SDL2-2.0.3
  - ./configure --prefix=$SDL2DIR
  - make
  - make install
  - sudo apt-get install -y libgl1-mesa-dev libopenal-dev libsndfile-dev
script:
  - bundle exec rake make